In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split as TTS
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv("pima-data.csv")

In [9]:
df.head(20)

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,6,148,72,35,0,33.6,0.627,50,1.3790,True
1,1,85,66,29,0,26.6,0.351,31,1.1426,False
2,8,183,64,0,0,23.3,0.672,32,0.0000,True
3,1,89,66,23,94,28.1,0.167,21,0.9062,False
4,0,137,40,35,168,43.1,2.288,33,1.3790,True
5,5,116,74,0,0,25.6,0.201,30,0.0000,False
6,3,78,50,32,88,31.0,0.248,26,1.2608,True
7,10,115,0,0,0,35.3,0.134,29,0.0000,False
8,2,197,70,45,543,30.5,0.158,53,1.7730,True
9,8,125,96,0,0,0.0,0.232,54,0.0000,True
10,4,110,92,0,0,37.6,0.191,30,0.0000,False
11,10,168,74,0,0,38.0,0.537,34,0.0000,True
12,10,139,80,0,0,27.1,1.441,57,0.0000,False
13,1,189,60,23,846,30.1,0.398,59,0.9062,True
14,5,166,72,19,175,25.8,0.587,51,0.7486,True
15,7,100,0,0,0,30.0,0.484,32,0.0000,True
16,0,118,84,47,230,45.8,0.551,31,1.8518,True
17,7,107,74,0,0,29.6,0.254,31,0.0000,True
18,1,103,30,38,83,43.3,0.183,33,1.4972,False
19,1,115,70,30,96,34.6,0.529,32,1.1820,True

In [10]:
df.loc[df['diastolic_bp'] == 0]

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
7,10,115,0,0,0,35.3,0.134,29,0.0000,False
15,7,100,0,0,0,30.0,0.484,32,0.0000,True
49,7,105,0,0,0,0.0,0.305,24,0.0000,False
60,2,84,0,0,0,0.0,0.304,21,0.0000,False
78,0,131,0,0,0,43.2,0.270,26,0.0000,True
81,2,74,0,0,0,0.0,0.102,22,0.0000,False
172,2,87,0,23,0,28.9,0.773,25,0.9062,False
193,11,135,0,0,0,52.3,0.578,40,0.0000,True
222,7,119,0,0,0,25.2,0.209,37,0.0000,False
261,3,141,0,0,0,30.0,0.761,27,0.0000,True
266,0,138,0,0,0,36.3,0.933,25,0.0000,True
269,2,146,0,0,0,27.5,0.240,28,0.0000,True
300,0,167,0,0,0,32.3,0.839,30,0.0000,True
332,1,180,0,0,0,43.3,0.282,41,0.0000,True
336,0,117,0,0,0,33.8,0.932,44,0.0000,False
347,3,116,0,0,0,23.5,0.187,23,0.0000,False
357,13,129,0,30,0,39.9,0.569,44,1.1820,True
426,0,94,0,0,0,0.0,0.256,25,0.0000,False
430,2,99,0,0,0,22.2,0.108,23,0.0000,False
435,0,141,0,0,0,42.4,0.205,29,0.0000,True
453,2,119,0,0,0,19.6,0.832,72,0.0000,False
468,8,120,0,0,0,30.0,0.183,38,0.0000,True
484,0,145,0,0,0,44.2,0.630,31,0.0000,True
494,3,80,0,0,0,0.0,0.174,22,0.0000,False
522,6,114,0,0,0,0.0,0.189,26,0.0000,False
533,6,91,0,0,0,29.8,0.501,31,0.0000,False
535,4,132,0,0,0,32.9,0.302,23,0.0000,True
589,0,73,0,0,0,21.1,0.342,25,0.0000,False
601,6,96,0,0,0,23.7,0.190,28,0.0000,False
604,4,183,0,0,0,28.4,0.212,36,0.0000,True
619,0,119,0,0,0,32.4,0.141,24,0.0000,True
643,4,90,0,0,0,28.0,0.610,31,0.0000,False
697,0,99,0,0,0,25.0,0.253,22,0.0000,False
703,2,129,0,0,0,38.5,0.304,41,0.0000,False
706,10,115,0,0,0,0.0,0.261,30,0.0000,True

In [11]:
print("ZERO value in  num_preg: {0}".format(len(df.loc[df['num_preg'] == 0])))
print("ZERO value in  glucose_conc: {0}".format(len(df.loc[df['glucose_conc'] == 0])))
print("ZERO value in  diastolic_bp: {0}".format(len(df.loc[df['diastolic_bp'] == 0])))
print("ZERO value in  insulin: {0}".format(len(df.loc[df['insulin'] == 0])))
print("ZERO value in  bmi: {0}".format(len(df.loc[df['bmi'] == 0])))
print("ZERO value in  diab_pred: {0}".format(len(df.loc[df['diab_pred'] == 0])))
print("ZERO value in  age: {0}".format(len(df.loc[df['age'] == 0])))
print("ZERO value in  skin: {0}".format(len(df.loc[df['skin'] == 0])))

ZERO value in  num_preg: 111
ZERO value in  glucose_conc: 5
ZERO value in  diastolic_bp: 35
ZERO value in  insulin: 374
ZERO value in  bmi: 11
ZERO value in  diab_pred: 0
ZERO value in  age: 0
ZERO value in  skin: 227

In [12]:
dependent_features = ['glucose_conc', 'diastolic_bp', 'insulin', 'bmi', 'diab_pred', 'age', 'skin']

In [13]:
for i in dependent_features:
    df[i].replace(0,df[i].mean(),inplace=True)

In [14]:
print("ZERO value in  num_preg: {0}".format(len(df.loc[df['num_preg'] == 0])))
print("ZERO value in  glucose_conc: {0}".format(len(df.loc[df['glucose_conc'] == 0])))
print("ZERO value in  diastolic_bp: {0}".format(len(df.loc[df['diastolic_bp'] == 0])))
print("ZERO value in  insulin: {0}".format(len(df.loc[df['insulin'] == 0])))
print("ZERO value in  bmi: {0}".format(len(df.loc[df['bmi'] == 0])))
print("ZERO value in  diab_pred: {0}".format(len(df.loc[df['diab_pred'] == 0])))
print("ZERO value in  age: {0}".format(len(df.loc[df['age'] == 0])))
print("ZERO value in  skin: {0}".format(len(df.loc[df['skin'] == 0])))

ZERO value in  num_preg: 111
ZERO value in  glucose_conc: 0
ZERO value in  diastolic_bp: 0
ZERO value in  insulin: 0
ZERO value in  bmi: 0
ZERO value in  diab_pred: 0
ZERO value in  age: 0
ZERO value in  skin: 0

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   num_preg      768 non-null    int64
 1   glucose_conc  768 non-null    float64
 2   diastolic_bp  768 non-null    float64
 3   thickness     768 non-null    int64
 4   insulin       768 non-null    float64
 5   bmi           768 non-null    float64
 6   diab_pred     768 non-null    float64
 7   age           768 non-null    int64
 8   skin          768 non-null    float64
 9   diabetes      768 non-null    bool
dtypes: bool(1), float64(6), int64(3)
memory usage: 54.9 KB

In [16]:
change_diab = {True: 1, False: 0}

In [18]:
df['diabetes'] = df['diabetes'].map(change_diab)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   num_preg      768 non-null    int64
 1   glucose_conc  768 non-null    float64
 2   diastolic_bp  768 non-null    float64
 3   thickness     768 non-null    int64
 4   insulin       768 non-null    float64
 5   bmi           768 non-null    float64
 6   diab_pred     768 non-null    float64
 7   age           768 non-null    int64
 8   skin          768 non-null    float64
 9   diabetes      768 non-null    int64
dtypes: float64(6), int64(4)
memory usage: 60.1 KB

In [20]:
df.head()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin,diabetes
0,6,148.0,72.0,35,79.799479,33.6,0.627,50,1.379000,1
1,1,85.0,66.0,29,79.799479,26.6,0.351,31,1.142600,0
2,8,183.0,64.0,0,79.799479,23.3,0.672,32,0.809136,1
3,1,89.0,66.0,23,94.000000,28.1,0.167,21,0.906200,0
4,0,137.0,40.0,35,168.000000,43.1,2.288,33,1.379000,1

In [39]:
from sklearn.model_selection import train_test_split as TTS

In [28]:
X = df.drop(['diabetes'],axis=1)
Y = df['diabetes'].values

In [35]:
X.head()

,num_preg,glucose_conc,diastolic_bp,thickness,insulin,bmi,diab_pred,age,skin
0,6,148.0,72.0,35,79.799479,33.6,0.627,50,1.379000
1,1,85.0,66.0,29,79.799479,26.6,0.351,31,1.142600
2,8,183.0,64.0,0,79.799479,23.3,0.672,32,0.809136
3,1,89.0,66.0,23,94.000000,28.1,0.167,21,0.906200
4,0,137.0,40.0,35,168.000000,43.1,2.288,33,1.379000

In [37]:
Y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0],
      dtype=int64)

In [40]:
X_train,X_test,Y_train,Y_test= TTS(X,Y,test_size=.20,random_state = 0)

# LogisticRegression

In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix

In [43]:
M1=LogisticRegression()

In [44]:
M1.fit(X_train,Y_train)

C:\Users\Omdutt\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [45]:
Y_pred = M1.predict(X_test)

In [46]:
accuracy_score(Y_test,Y_pred)

0.8051948051948052

In [47]:
cfm = confusion_matrix(Y_test,Y_pred)
cfm

array([[97, 10],
       [20, 27]], dtype=int64)

# DecisionTreeClassifier

## 1. CART

In [49]:
from sklearn.tree import DecisionTreeClassifier

In [59]:
M2 = DecisionTreeClassifier(criterion='gini', max_depth=4)

In [60]:
M2.fit(X_train,Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [61]:
Y_pred = M2.predict(X_test)

In [62]:
accuracy_score(Y_test,Y_pred)

0.7662337662337663

In [63]:
cfm = confusion_matrix(Y_test,Y_pred)
cfm

array([[91, 16],
       [20, 27]], dtype=int64)

## ## ID3

In [71]:
M3 = DecisionTreeClassifier(criterion='entropy',max_depth=7)

In [72]:
M3.fit(X_train,Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=7, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [73]:
Y_pred = M3.predict(X_test)

In [74]:
accuracy_score(Y_test,Y_pred)

0.7987012987012987

In [75]:
cfm = confusion_matrix(Y_test,Y_pred)
cfm

array([[93, 14],
       [17, 30]], dtype=int64)

## RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
random_forest_model = RandomForestClassifier(random_state=10)